### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by Depaulicious** [kkroening/ffmpeg-python#1]
Hello @kkroening,
I was going to make something like this for a work project, but then found your module.
I gave a quick look and it seems pretty nice, but I see a only a few filters are supported and there's no documentation

Are you going to write any documentation for this and add more filters?

I may submit PRs to add a couple of them, I need effects like scale (zoom), sepia, greyscale and stuff like that, which I don't see.

**Comment by kkroening** [comment]
Hey @Depaulicious,

Thanks for your interest & contributions.

So far it's an initial POC, but I'm still actively working on it - currently adding support for streaming to/from JACK Audio Connection Kit.

I'd definitely like to improve the documentation:
- Accurate pydocs to list help for available functions/filters (e.g. via `help()`)
- Full usage docs
- Development/contribution guide
- Code examples

Haven't gotten to it yet, but since there's interest I'll bump the priority.

I see that you submitted some PRs and look forward to reviewing them this evening. Will keep you posted.

Thanks!
Karl

**Comment by kkroening** [comment]
FYI, I made a new branch that maintains the same API but is implemented in a much smoother, simpler and more extensible way, inspired by the args/kwargs changes you submitted.

Here's the refactored code:
https://github.com/kkroening/ffmpeg-python/blob/feature-1/ffmpeg/__init__.py

Should be a lot easier to implement new filters now, and documentation will be vanilla pydocs.

I haven't gotten a chance to get the pydocs added yet but I'll do that next.

**Comment by kkroening** [comment]
`feature-1` has been merged to master. API documentation can be seen by clicking the [API Reference](https://kkroening.github.io/ffmpeg-python/) link in the readme, or running `import ffmpeg; help(ffmpeg)` in the python REPL.

Thanks @Depaulicious
