### ISSUE TITLE
Does not work with Python 3

### ISSUE THREAD

**Issue by benjolitz** [kkroening/ffmpeg-python#10]
Perhaps one should add a Python 2 restrictor on the setup.py? Or make use of ``six`` for supporting both? Or port to Python 3?

```
(cpython36) benjolitz-laptop:~/software$ python
Python 3.6.0 (default, Dec 24 2016, 08:01:42)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ffmpeg
>>> i = ffmpeg.input('/Users/BenJolitz/Downloads/b195bd7c-aa7b-44c4-83a5-2c12e77a8784.mov')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/BenJolitz/.virtualenvs/cpython36/lib/python3.6/site-packages/ffmpeg/_ffmpeg.py", line 15, in input
    return InputNode(input.__name__, filename=filename)
  File "/Users/BenJolitz/.virtualenvs/cpython36/lib/python3.6/site-packages/ffmpeg/nodes.py", line 35, in __init__
    super(InputNode, self).__init__(parents=[], name=name, *args, **kwargs)
  File "/Users/BenJolitz/.virtualenvs/cpython36/lib/python3.6/site-packages/ffmpeg/nodes.py", line 14, in __init__
    self._update_hash()
  File "/Users/BenJolitz/.virtualenvs/cpython36/lib/python3.6/site-packages/ffmpeg/nodes.py", line 26, in _update_hash
    my_hash = hashlib.md5(json.dumps(props, sort_keys=True)).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
>>>
```

**Comment by Depaulicious** [comment]
In my opinion `six`'s "natives" are a little bit a pain in the neck. I'd just prepend `b` to every string; python 2 ignores it and reads it as `str`, python3 interprets it as `bytes` instead of `str`, making this part work.

Or simply add at the beginning:

```python
if sys.version.major == 2:
    _str = str
    bytes = str
    str = unicode
```
Then make sure the string in question is _casted_ to `bytes`.

**Comment by benjolitz** [comment]
Python 3 and 2 also recognize `u'unicode str'`, so using both `b` and `u` prefixes would work well. Also help in self documenting your data types (at least for byte strings and unicode strings).

**Comment by kkroening** [comment]
Hey thanks for pointing this out. I'll change `setup.py` for now and then add Python 3 support as soon as I can. Will keep you posted.

**Comment by kkroening** [comment]
Okay, added Python 3 support, as well as CI testing for Python 3.3, 3.4, 3.5, and 3.6.

Here's the PR, in case either of you wouldn't mind taking a look for sanity checking: https://github.com/kkroening/ffmpeg-python/pull/12

If you have any suggestions/feedback on the PR let me know, otherwise I'll merge it sometime tomorrow.

Thanks!
