### ISSUE TITLE
nb_frames not defined

### ISSUE THREAD

**Issue by greenpdx** [kkroening/ffmpeg-python#110]
I am trying to do facial recognition from video.  when I try to get the number of frames. I get undefined field.  

I have pasted to code and results

``` python
probe = ffmpeg.probe('alice.webm')
video_info = next((stream for stream in probe['streams'] if stream['codec_type'] == 'video'), None)
width = int(video_info['width'])
height = int(video_info['height'])
print(video_info)
```

{'index': 0, 'codec_name': 'vp9', 'codec_long_name': 'Google VP9', 'profile': 'Profile 0', 'codec_type': 'video', 'codec_time_base': '100/2997', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'width': 1280, 'height': 720, 'coded_width': 1280, 'coded_height': 720, 'has_b_frames': 0, 'sample_aspect_ratio': '1:1', 'display_aspect_ratio': '16:9', 'pix_fmt': 'yuv420p', 'level': -99, 'color_range': 'tv', 'chroma_location': 'left', 'field_order': 'progressive', 'refs': 1, 'r_frame_rate': '2997/100', 'avg_frame_rate': '2997/100', 'time_base': '1/1000', 'start_pts': 7, 'start_time': '0.007000', 'disposition': {'default': 1, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}, 'tags': {'HANDLER_NAME': 'VideoHandler', 'ENCODER': 'Lavc57.107.100 libvpx-vp9', 'DURATION': '00:06:29.029000000'}}

**Comment by kkroening** [comment]
I'm not seeing what part of that code is generating `nb_frames not defined`.

In any case, if you're trying to find the duration of your video, it looks like you'll have to parse the `DURATION` field in `tags`.

i.e.
```python
duration_text = video_info['tags']['DURATION']
duration_parts = duration_text.split(':')
duration = (duration[0] * 60 + duration[1]) * 60 + duration[2]
```
Something like that, anyways. Then multiply by frame rate to get the number of frames.

**Comment by greenpdx** [comment]
Yes, the error was later in the code, but I added printing video_info for debugging.  Thanks, that was what I was afraid of.  It has a frame rate of 2997/100.

**Comment by golyalpha** [comment]
This issue has been closed for a while, but this is what comes up first when I google nb_frames, so, for clarification:

Somehow some video files (depending on container, maybe?) don't have the `nb_frames` stream attribute.

A quick and dirty way to get frame count from those types of files is to add the `count_packets` option to ffprobe. That will add the `nb_read_packets` attribute, which should most of the time be the same as the amount of frames in the video stream.

Alternatively, if accuracy is more desirable for possible edge cases, the option `count_frames` can be used, which adds `nb_read_frames` attribute. This option actually decodes the stream and counts the actual frames within it, rather than just demuxing the container and counting the number of packets in a stream, which results in a 100% accurate count, but is much slower.
