### ISSUE TITLE
Reading specific frames from a video

### ISSUE THREAD

**Issue by MrinalJain17** [kkroening/ffmpeg-python#114]
So, I was wondering how to read a video, **frame-by-frame** and select only specific frames.

For example - 

Say the video has 240 frames in total, and I want to read frames at index `[0, 10, 20, 30, and so on..]`. How can this be achieved?

Note that reading frame-wise is important in case the video is too large to be in the memory.

**Comment by kkroening** [comment]
Check out [this single-frame example](https://github.com/kkroening/ffmpeg-python/tree/master/examples#read-single-video-frame-as-jpeg-through-pipe) and [numpy array example](https://github.com/kkroening/ffmpeg-python/tree/master/examples#convert-video-to-numpy-array).

I recommend working with the video in something like numpy since it's much easier to work with, unless you have some other use case that precludes this.

Here's one of the easiest ways to read a single frame:
```python
out, _ = (
    ffmpeg
    .input('in.mp4')
    .filter('select', 'gte(n, {})'.format(frame_num))
    .output('pipe:', format='rawvideo', pix_fmt='rgb24', vframes=1)
    .run(capture_stdout=True)
)
video = (
    np
    .frombuffer(out, np.uint8)
    .reshape([-1, height, width, 3])
)
```
One quick 'n dirty way to do this would be to wrap the above and exec ffmpeg for each frame. Depending on the number of frames you're trying to extract, this is somewhere on the spectrum between "entirely practical" and "totally insane and inefficient."

A slightly improved version would use input seeking (ffmpeg `-ss` option) so that ffmpeg goes straight to the frame you want instead of twiddling its thumbs skipping over the initial frames you don't want. Depending on your use case, this might be the best bet, with the caveat that `-ss` only takes timecodes and not frame numbers (if I understand correctly; could be wrong though), so you have to do some careful math and deal with rounding errors to get the exact frame you want.

If you don't use `-ss` I don't know that there's any way to have ffmpeg actually skip over the frames you don't want. It basically has to go through every single frame of the video and then filter out the frames you don't want, using something like the `select` operator. If you're pulling out a large percentage of the total number of frames, say 20%, then this is perfectly reasonable. But if you're pulling a handful of frames from a 2 hour video, then it's probably best to just run ffmpeg either multiple times with a different `-ss` or with multiple inputs (each with different `-ss` params).

The best bet is to refer to the examples and look closely at the ffmpeg documentation. There isn't a one-size-fits-all for this so you'll have to see what works best for your particular use case.

**Comment by MrinalJain17** [comment]
Hi @kkroening  

I have actually created a utility for frame extraction from videos ([link to repo](https://github.com/MrinalJain17/mydia)), and up until now, I've been using [scikit-video](http://www.scikit-video.org/stable/) under the hood. But the development on scikit-video seems to be stagnant and therefore I was looking for other libraries that I can use instead.

Also, thanks for your detailed explanation - I'll try out the techniques you mentioned to see if they fit.

**Comment by sailist** [comment]
you  can try this
```python

process = (
    ffmpeg
    .input(video_path,vsync=0)
    .filter('select', 'mod(n,2)')
    .filter('scale', size='200x200')
    .output('pipe:', format='rawvideo', pix_fmt='rgb24')
    .run_async(pipe_stdout=True, pipe_stderr=True)
)

out, err = process.communicate()


video = (
    np
    .frombuffer(out, np.uint8)
    .reshape([-1, 200, 200, 3])
)

```

or 

```
out, err = (
    ffmpeg
    .input(video_path,vsync=0)
    .filter('select', 'mod(n,2)')
    .filter('scale', size='200x200')
    .output('pipe:', format='rawvideo', pix_fmt='rgb24',)
#     .output('pipe:', format='rawvideo', pix_fmt='rgb24',vframes=500) # select top 500
    .run(capture_stdout=True)
)
...
```
