### ISSUE TITLE
How to read a video frame from a pipe, for Opencv

### ISSUE THREAD

**Issue by inventer88** [kkroening/ffmpeg-python#120]
I'm trying to extract a frame from node v1 and get it processed in Opencv(almost realtime). Also does this wrapper handle rtmp input. 

This is my attempt so far.
########################
#!/usr/bin/env python3
import ffmpeg
import numpy as np
import sys
import cv2
in1 = ffmpeg.input('video.mp4')

v1 = in1['v'].hflip().drawbox(50, 50, 120, 120, color='red', thickness=5)
a1 = in1['a']

#v13 = v1.output('pipe:', vframes=1, format='image2', vcodec='mjpeg')
#v14 = np.frombuffer(v13, np.uint8).reshape([-1, height, width, 3])
#print(type(v14))
joined = ffmpeg.concat(v1,a1,v=1,a=1).node
v2 = joined[0]
a2 = joined[1].filter('volume',0.8)
out = ffmpeg.output(v2, a2, 'out.mp4')
######################

**Comment by kkroening** [comment]
If you can get OpenCV to read from a pipe rather than trying to write to a file or read frame by frame, you'll avoid a lot of complexity + overhead.

As OpenCV uses ffmpeg under the covers, you might be able to pass `pipe:` as the input filename to `cv2.VideoCapture`, and then when you build your ffmpeg pipeline that you're feeding to OpenCV, use `.output('pipe:')` with a raw videos stream. i.e. something like this:

```bash
in1 = ffmpeg.input('video.mp4')

v1 = in1['v'].hflip().drawbox(50, 50, 120, 120, color='red', thickness=5)
a1 = in1['a']

joined = ffmpeg.concat(v1,a1,v=1,a=1).node
v2 = joined[0]
out = ffmpeg.output(v2, 'pipe:')
args = ffmpeg.compile(out)
child_proc = subprocess.Popen(args, stdout=subprocess.PIPE)
cv2_stream = cv2.VideoCapture('pipe:{}'.format(child_proc.stdout.fileno()))
```

I haven't worked with OpenCV much personally and I haven't tested the above code so I have no idea whether it actually works, but it might be an idea for where to start.

I'm not sure what you're trying to do with the audio though. AFAICT OpenCV doesn't work with audio.

**Comment by kkroening** [comment]
As for `rtmp`, it should be possible given the right `.input` args.
