### ISSUE TITLE
ffmpeg Jupyter wrapper kernel?

### ISSUE THREAD

**Issue by psychemedia** [kkroening/ffmpeg-python#148]
I was having a look at [metakernel](https://github.com/Calysto/metakernel) last night, which helps provide magics when creating Jupyter wrapper kernels using `Pexpect` around command line applications.

One of the things I realised was that with a command-line application wrapped in a Jupyter kernel, we can call it from a web page using something like the Thebelab js client in a web page to fire up a Binderhub environment running the kernel; which means that eg you can run arbitrary gnuplot scripts from a form in a web page on a remote gnuplot kernel and display the output chart back in the web page ([example](https://blog.ouseful.info/2018/12/06/jupyter-is-not-just-notebooks/)).

So I wonder: how easy would it be to use `ffmpeg-python` as the basis of a Jupyter wrapper kernel / metakernel and thence use it in a ThebeLab context?

**Comment by kkroening** [comment]
Check out the [Jupyer Stream Editor example](https://github.com/kkroening/ffmpeg-python/blob/master/examples/README.md#jupyter-stream-editor) (+ [source notebook](https://github.com/kkroening/ffmpeg-python/blob/master/examples/ffmpeg-numpy.ipynb)). Is that the sort of thing that you're after?

**Comment by psychemedia** [comment]
Ish but more... ability to use something like an %%ffmpeg magic or kernel code cell to call ffmpeg simply and directly. cf the gnuplot_kernel for calling gnuplot.

**Comment by 153957** [comment]
And then use the unwieldy CLI of ffmpeg? Or what are you getting at? Why is using ffmpeg-python as shown in the example not good enough? it is very explicit and clear. The main bonus of ffmpeg-python is that it allows you to create readable processing/filters/etc, unlike the ffmpeg CLI.

**Comment by psychemedia** [comment]
Agreed... what I'm trying to think towards is a way of packaging things so that users can run something lile ffmpeg-pyhton. I work in a distance ed setting and whenever students have to install any s/w, things can go badly wrong.  What I'm looking for solutions are things like ffmpeg-python to provide a nice UI and things like 'runnable kernels', eg provided via a lite version of Binderhub that serves just the kernel as a running remote kernel, rather than a whole notebook.

**Comment by kkroening** [comment]
Yeah I don't know why you'd want to use the magic-hack. Just because you _can_ doesn't mean you _should_.

There are a few things you're talking about here, and primarily there's the _what_ versus the _how_.

The "what": easy to use, web-hosted interface to ffmpeg, preferably with some sort of UI.

The proposed "how": jupyter magic-hack.

There's a big jump in going from the _what_ to the _how_ there. There's potential value in the _what_ but it's vague, and _why_ that approach is fundamentally any better than any other approach is unclear.

If you can elaborate more on what you're really trying to accomplish and what you find unappealing about the existing jupyter demo (which we could hopefully improve if there's value in doing so, or at least understand what makes it fundamentally of no use over jupyter magic) then we might be able to help, but there's not a lot to go off of here at the moment.

**Comment by kkroening** [comment]
Thanks for your interest in the project. I want to be of help to you but I need a bit more clear than _want something better than the existing jupyter demo in some sort of way and with some sort of eaay-to-use UI that makes it simple for people to learn how to use ffmpeg while hiding ffmpeg behind magic._

**Comment by kkroening** [comment]
I'm going to close this for now. Thanks for the link anyways @psychemedia. Will keep it in mind for future reference. Feel free to add to this issue if you'd like to discuss further.
