### ISSUE TITLE
How to add multiple -i options

### ISSUE THREAD

**Issue by CubicPill** [kkroening/ffmpeg-python#163]
Hi there, I want to use a palette to generate GIF from APNG files. In command line, I could just type the following to use palette:
```
ffmpeg -i <apng file> -i <palette> -lavfi paletteuse -y <out>
```
But I don't know how to do this using `ffmpeg-python`. I looked into the code and it seems only one `-i` is currently supported. Is there another way to do so?

Thanks!

**Comment by kkroening** [comment]
Take a look at the [main example](https://github.com/kkroening/ffmpeg-python#complex-filter-graphs) in the readme. Note how there are multiple calls to `ffmpeg.input`, and both of those get fed into `ffmpeg.concat`.

In your case however, instead of using the `concat` filter, you're trying to use `paletteuse`, so you'll call `ffmpeg.filter([in1, in2], 'paletteuse', ...)` instead.
