### ISSUE TITLE
Error with import_module

### ISSUE THREAD

**Issue by Tecnico1** [kkroening/ffmpeg-python#272]
Try this:

```
import importlib
importlib.import_module('ffmpeg-python")  # Error
```

When installing ffmpeg-python with pip, no folder "ffmpeg-python" is created in the site-packages folder, in my case only the folder "ffmpeg_python-0.2.0.dist-info" is created.

**Comment by spirulence** [comment]
@Tecnico1 makes sense to me. Sorry it caused you alarm!

There's a long tradition of python modules (usually bindings for tools written in other languages) that are installed using one name but provide one or more modules under a slightly different name.

In the case of this library, the README pretty clearly states that you use `import ffmpeg`, so I don't see the issue here.

**Comment by Tecnico1** [comment]
Thanks for your response.

Then, how have I to load the ffmpeg-python module with importlib?

**Comment by spirulence** [comment]
This works on my machine:
```
import importlib
ffmpeg = importlib.import_module('ffmpeg')
```
Good luck with whatever you're up to!

**Comment by Tecnico1** [comment]
Thanks. Best regards.
