### ISSUE TITLE
How do you record the screen?

### ISSUE THREAD

**Issue by NullVoxPopuli** [kkroening/ffmpeg-python#35]
I've been looking for python bindings for a screen recorder, and I can't seem to get anywhere near 60fps.

PIL.ImageGrab is about 8-9 FPS
mss.grab is about 15-16 FPS

This is on an i7 2600K as well... so -- really surprised how slow those two are.

**Comment by kkroening** [comment]
Doing raw video processing directly in Python is going to be slow no matter what. Libraries like `PIL` are designed to work with all of the image data in memory directly accessible from Python, but it's slow, and there's a limit to how fast you can process image data in this manner.

With `ffmpeg-python`, instead the processing is done indirectly by shelling out to a separate `ffmpeg` process. All of the work is done in `ffmpeg` so it's a lot faster, but the downside is that you don't work with individual frames.

So it depends what you're trying to do. Does the captured video data just need to go to a file, or streamed over a socket, or do you also need to do additional processing on the video?

- Streaming to a file is easy - just specify the correct output.
- Streaming across a socket requires simply having ffmpeg write to stdout (probably `.output('file:stdout')` or something like that)
- If you have to do additional processing on the video data, it's best to do it with ffmpeg rather than trying to do frame-by-frame processing in python, which is a computation bottleneck.
