### ISSUE TITLE
Write better documentation

### ISSUE THREAD

**Issue by Depau** [kkroening/ffmpeg-python#37]
As the project is expanding I'm seeing a lot of unclarity in the code.

You now have some objects that are children of `Node`, some that are children of `Stream`. I read everywhere `outgoing_edge`, `incoming_edge`, `node`, but it's unclear what they do and how the graph is resolved: it's all buried in Python syntactic sugar, which is not a bad thing if properly documented.

Could you please explain the current project structure, what each object exactly does, how the graph paths are visited to generate the command line? I would be happy to help you with the project if only I could understand what is going on under the hood.

Thank you!

I'm trying to implement the audio thing (#26) but I can't figure out how to add an outgoing edge to a stream and represent it as `:a` etc.

**Comment by kkroening** [comment]
Yeah, that `dag.py` code is messy and confusing. I want to clean it up and make it more understandable. It should be relatively easy to do a refactor without changing the external API.

In particular, I plan on pulling in this library for doing graph/dag processing: [daglet](https://github.com/kkroening/daglet). That should clean things up and make it so that the graph processing is in one self-contained place.

That repo is still pretty new and needs more documentation, so I'll get that done before pulling it into `ffmpeg-python`.

**Comment by kkroening** [comment]
The nice thing about that library is that it can be used for all sorts of related things with plenty of examples and documentation. That way it's easier to understand since there are plenty of examples.

**Comment by Depaulicious** [comment]
That's nice, I too like to keep things as generic as possible
