### ISSUE TITLE
Windows 10 doesn't work with ffmpeg-python

### ISSUE THREAD

**Issue by DiegoDev-It** [kkroening/ffmpeg-python#528]
On Windows 10 I tried to install ffmpeg-python with pip3 install ffmpeg-python, works but... 
`ModuleNotFoundError: No module named 'ffmpeg'`
On Linux the same script and the same installing method works... but on Windows 10 no.
Why?

**Comment by raulpy271** [comment]
Do you have FFmpeg installed on Windows?

**Comment by DiegoDev-It** [comment]
> 
> 
> Do you have FFmpeg installed on Windows?

Yes yes, and is correctly installed. Also I tried to drag and dropping ffmpeg in python modules directory, installing requirements but `File "C:\Program Files\Python39\lib\ffmpeg\__init__.py", line 2, in <module>
    from . import nodes
  File "C:\Program Files\Python39\lib\ffmpeg\nodes.py", line 3, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'` so this isn't the way.

**Comment by raulpy271** [comment]
Note that what this library does is convert python code to a ffmpeg command, so you should have the ffmpeg installed.

I guess that what you have installed is the package from this command `pip install ffmpeg`, which is wrong because fffmpeg isn't a python module. To install the correct app you should see the download instruction on the ffmpeg [home page](https://ffmpeg.org/).

To have sure that you installed the right thing, you should type ffmpeg commands in a terminal, as it `ffmpeg -version`.

**Comment by DiegoDev-It** [comment]
> 
> 
> Note that what this library does is convert python code to a ffmpeg command, so you should have the ffmpeg installed.
> 
> I guess that what you have installed is the package from this command `pip install ffmpeg`, which is wrong because fffmpeg isn't a python module. To install the correct app you should see the download instruction on the ffmpeg [home page](https://ffmpeg.org/).
> 
> To have sure that you installed the right thing, you should type ffmpeg commands in a terminal, as it `ffmpeg -version`.

I just checked again, and `ffmpeg -version` works.
