### ISSUE TITLE
ffmpeg.global_args() doesn't work as expected

### ISSUE THREAD

**Issue by hkgeex** [kkroening/ffmpeg-python#540]
I'm trying to run this command:

```
['ffmpeg', '-re', '-i', 'foo.mp4', '-f', 'flv', 'rtmp://foo/bar']
```

which I expected to look like this in Python:

```
ffmpeg.global_args('-re').input('foo.mp4').output('rtmp://foo/bar', format='flv').run()
```

which doesn't work.  I had to do this instead:

```
ffmpeg.input('foo.mp4').output('rtmp://foo/bar', format='flv').run(['ffmpeg', '-re'])
```

Doing `-re` in the run cmd feels wrong - can we do this via global_args?

**Comment by hkgeex** [comment]
OK, I figured it out for `-re`[*], but the question still applies if I'd like to use `-hide_banner` or any other ffmpeg global options.

[*]
```
ffmpeg.input('foo.mp4', re=None).output('rtmp://foo/bar', format='flv').run()
```

**Comment by Bananaman** [comment]
`global_args()` is used like this: https://github.com/kkroening/ffmpeg-python/issues/388

But it doesn't work in the outdated version of the library distributed on PyPi/pip. And the new method is not documented online: https://kkroening.github.io/ffmpeg-python/

So that may be why it doesn't work for you. You're supposed to put it in the `.run()` args on older versions. Read the docs for how to add global arguments to `run()`. Good luck.

**Comment by hkgeex** [comment]
Thanks!

Yeah, I tried calling `global_args()` right before `run()`, but if I remember correctly it placed it at the end and wouldn't work.  I suppose I'll keep it in the `.run()` arg for now.

**Comment by Bananaman** [comment]
@hkgeex Yeah I guess it's cleaner to put them in `run()` than in `input()`. :-)

Also check out this library: https://github.com/kkroening/ffmpeg-python/issues/520#issuecomment-834700405

It looks like a much better library (it implements every ffmpeg filter and does it in a very object oriented way), but it's brand new and unproven track record.
