### ISSUE TITLE
Permission denied when cloning

### ISSUE THREAD

**Issue by turrnut** [kkroening/ffmpeg-python#776]
When I tried to clone the repository according to the docs
```
C:\test\discord>git clone git@github.com:kkroening/ffmpeg-python.git
```
I got the following error: 
```
Cloning into 'ffmpeg-python'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I am using windows 11, python 3.10, pip 23.1.2 Help would be appreciated.

**Comment by charlienewey** [comment]
The error message tells you what the problem is.

You are getting “permission denied” errors because your SSH public key is not registered with your GitHub account.

You need to either add your public key to your GitHub account, or generate an access password/access token in your account settings and clone the repo using the HTTPS URL instead.

This might help:
https://medium.com/devops-with-valentine/2021-how-to-set-up-your-ssh-key-for-github-on-windows-10-afe6e729a3c0

**Comment by turrnut** [comment]
Ok, thanks, this solved my problem
