### ISSUE TITLE
Replace "filter_" with something that tries to resolve the filter automatically

### ISSUE THREAD

**Issue by Depaulicious** [kkroening/ffmpeg-python#8]
I think we could change the way the module works by getting somewhere the list of available filters and mapping them manually to a catch-all callable that that generates filter args automatically.

I haven't tried doing it already because there are some things to discuss, like how to distinguish single-input filters from multi-input, and how to decide whether a filter is acceptable or not.

**Comment by kkroening** [comment]
Hey sorry for the late reply. I like the idea of auto-generating filters.

A few downsides to doing a custom callable though:
- code completion not available in IDEs
- docstrings not avaiable in `help()`
- autocompletion not available in REPL
- difficult/impossible to have module-level `__call__` operator (for non-fluent interface, e.g. `ffmpeg.hflip(parent)` instead of parent.hflip()`)

Another approach might be to auto-generate the functions and assign them to the module like this:
```
def _generate_filter(name):
    @operator(name=name)
    def func(parent, *args, **kwargs):
        return filter_(parent, name, *args, **kwargs)
    func.__name__ = name
    globals()['name'] = func

_filter_names = [
    'drawgraph',
    'interleave',
    ...
]
[_generate_filter(_name) for _name in _filter_names]
```
It should allow code completion, auto-generated docstrings, and work consistently in both fluent/non-fluent interfaces.

I'll have to come back to it after the other stuff I'm working on.  If it's holding anything up for you let me know

Thanks for the suggestion

**Comment by Depaulicious** [comment]
Yes, the latter is what I thought of.

**Comment by kkroening** [comment]
Huh, looks like `ffmpeg -filters` gives useful information:
```
 T.C volume            A->A       Change input volume.
 ... volumedetect      A->A       Detect audio volume.
 ... aevalsrc          |->A       Generate an audio signal generated by an expression.
 ... anoisesrc         |->A       Generate a noise audio signal.
 ... anullsrc          |->A       Null audio source, return empty audio frames.
 ... sine              |->A       Generate sine wave audio signal.
 ... anullsink         A->|       Do absolutely nothing with the input audio.
 ... alphaextract      V->N       Extract an alpha channel as a grayscale image component.
 ... alphamerge        VV->V      Copy the luma value of the second input into the alpha channel of the first input.
 TS. atadenoise        V->V       Apply an Adaptive Temporal Averaging Denoiser.
 TS. avgblur           V->V       Apply Average Blur filter.
 T.. bbox              V->V       Compute bounding box for each frame.
 ... bench             V->V       Benchmark part of a filtergraph.
 T.. bitplanenoise     V->V       Measure bit plane noise.
 ... blackdetect       V->V       Detect video intervals that are (almost) black.
 ... blackframe        V->V       Detect frames that are (almost) black.
 TS. blend             VV->V      Blend two video frames into each other.
 T.. boxblur           V->V       Blur the input.
 TS. bwdif             V->V       Deinterlace the input image.
```
It even includes input/output specifications to tell how many input/output streams each filter expects. Should be able to parse this and auto-generate filter functions with simple docstrings.

**Comment by Depaulicious** [comment]
Do you think this should be done at runtime or statically?

**Comment by kkroening** [comment]
Good question. A few options, each with pros and cons:
- Development time (static): run a script that autogenerates some python or a `.json` or `.yaml` file that contains the filter info. _Pros_: eliminates runtime overhead. _Cons_: different ffmpeg builds may have different filters, so some of the filters might not be available for whoever's installing `ffmpeg-python`.
- Installation time (semi-dynamic): generate filter info when `ffmpeg-python` pip package is being installed. _Pros_: runs ffmpeg on the system of whoever's installing it and thus has accurate list of filters. _Cons_: may not use the ffmpeg executable (which is probably a showstopper, since the correct executable may not even be available at installation time).
- Runtime (dynamic): run ffmpeg as soon as `ffmpeg-python` is imported. _Pros_: has accurate list of filters. _Cons_: adds runtime overhead and either uses the wrong ffmpeg executable or requires additional code changes.

So I'm thinking static is the only approach that really makes sense.

**Comment by kkroening** [comment]
Could also go with static by default, but then add a `ffmpeg.detect_filters('/path/to/ffmpeg-command')` sort of deal.

Or `ffmpeg.use_cmd('/path/to/ffmpeg-command', detect_filters=True)`

Or something along those lines

**Comment by Depaulicious** [comment]
I like both the approaches in the last message. It makes sense to override the default ffmpeg executable at module level, and update filters at runtime.

**Comment by Beefster09** [comment]
Why not use __getattr__?

It would only work for chained calls, but maybe that's not so bad since most filters only take one input argument.

**Comment by kkroening** [comment]
I'm gonna say no to any of the magical `__call__` or `__getattr__` behavior because it would be a maintenance nightmare. Imagine if people are using some filter we haven't implemented yet and it has weird quirks due to automagically trying to map `.somefilter(somearg='whatever')` and now people rely on that quirk. If we ever go to do a real implementation of that filter we have to maintain compatibility for that quirk, lest we break things for people.

`.filter_` should basically do everything that would be able to be done with `__getattr__` or whatever and make it clear that the user is in a bit of uncharted territory and should use caution and/or submit a feature request to have an official implementation of the filter in question.
